set autocommit off;

define PathToCSVFiles='C:\Users\tb\Desktop\Sandkasten\AdventureWorksDW2014_EXA\';

IMPORT INTO ADVENTUREWORKSDW2014."DimAccount" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\DimAccount.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."DimCurrency" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\DimCurrency.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."DimCustomer" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\DimCustomer.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."DimDate" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\DimDate.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."DimDepartmentGroup" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\DimDepartmentGroup.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."DimEmployee" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\DimEmployee.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."DimGeography" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\DimGeography.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."DimOrganization" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\DimOrganization.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."DimProduct" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\DimProduct.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."DimProductCategory" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\DimProductCategory.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."DimProductSubcategory" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\DimProductSubcategory.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."DimPromotion" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\DimPromotion.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."DimReseller" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\DimReseller.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."DimSalesReason" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\DimSalesReason.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."DimSalesTerritory" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\DimSalesTerritory.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."DimScenario" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\DimScenario.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."FactAdditionalInternationalProductDescription" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\FactAdditionalInternationalProductDescription.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."FactCallCenter" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\FactCallCenter.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."FactCurrencyRate" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\FactCurrencyRate.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."FactFinance" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\FactFinance.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."FactInternetSales" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\FactInternetSales.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."FactInternetSalesReason" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\FactInternetSalesReason.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."FactProductInventory" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\FactProductInventory.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."FactResellerSales" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\FactResellerSales.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."FactSalesQuota" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\FactSalesQuota.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."FactSurveyResponse" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\FactSurveyResponse.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."NewFactCurrencyRate" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\NewFactCurrencyRate.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;

IMPORT INTO ADVENTUREWORKSDW2014."ProspectiveBuyer" FROM LOCAL CSV FILE '&PathToCSVFiles\Data\ProspectiveBuyer.csv.gz' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP=1;


commit;

